name: Deploy Frontend

on:
  push:
    branches:
      - homologacao

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app/frontend
            git pull origin homologacao
            docker compose down
            docker compose up -d --build
            docker system prune -f
